import tkinter as tk
from tkinter import messagebox
import time
import random
import ctypes
import os

class TypingSpeedTest:
    def __init__(self, root):
        self.root = root
        self.root.title("Typing Speed Test Arcade")
        self.root.geometry("600x550")
        self.root.config(bg="#1e1e2e")
        
        self.mci = ctypes.windll.winmm.mciSendStringW
        
        self.sample_texts = [
            "Python is an interpreted high level programming language known for its great readability.",
            "The quick brown fox jumps over the lazy dog while the autumn wind blows across the open field.",
            "Developing software requires patience logical thinking continuous learning and attention to detail.",
            "Artificial intelligence is transforming industries by automating tasks and analyzing massive data.",
            "Light from the Sun takes approximately eight minutes and twenty seconds to reach Earth, meaning we always look into the past.",
            "Neutron stars are so incredibly dense that a single teaspoon of their material would weigh billions of tons on Earth.",
            "Venus is the hottest planet in our solar system, with a surface temperature hot enough to melt lead due to a runaway greenhouse effect.",
            "The observable universe contains an estimated two trillion galaxies, each hosting billions of unique solar systems and planets.",
            "In the center of the Milky Way lies Sagittarius A*, a supermassive black hole with a mass four million times greater than our Sun.",
            "Quantum entanglement allows two isolated particles to interact instantly across vast cosmic distances, which Einstein called spooky action at a distance.",
            "Atoms are mostly empty space; if you removed all the dead space from humanity's atoms, the entire human race could fit inside an apple.",
            "According to the wave-particle duality principle, light behaves simultaneously as both a continuous wave and a stream of discrete particles.",
            "Electrons do not orbit an atom's nucleus like planets; instead, they exist in a cloud of mathematical probabilities called orbitals.",
            "At absolute zero, which is the coldest possible temperature in the universe, all classical thermodynamic motion of atomic particles completely stops.",
            "Earth's magnetic field, which shields our atmosphere from deadly solar radiation, is generated by liquid iron moving in the outer core.",
            "Bananas are naturally radioactive because they contain high levels of potassium-40, though you would need to eat millions at once to suffer harm.",
            "A single bolt of lightning contains enough electrical energy to power an average home for several months, reaching temperatures hotter than the Sun.",
            "Trees talk to each other using an underground network of fungi, sharing vital nutrients and warning neighbors about incoming insect attacks.",
            "Water is one of the rare compounds that expands when it freezes, which allows ice to float and preserves aquatic life during winter.",
            "The human brain contains roughly eighty-six billion neurons, generating enough electrical power to light up a small, low-wattage LED bulb.",
            "If you uncoiled all the strands of DNA inside a single human body, the total length would stretch from Earth to Pluto and back.",
            "Absolute depth in the ocean is found at the Mariana Trench, a location deeper than Mount Everest is tall.",
            "Modern computer microchips contain billions of transistors packed onto a piece of silicon no larger than a human fingernail.",
            "The first digital computer, known as the ENIAC, weighed more than twenty-seven tons and occupied an entire room to process basic math.",
            "Honey never spoils; archaeologists have excavated ancient Egyptian tombs containing three-thousand-year-old honey jars that are still perfectly edible."
        ]
        
        self.target_text = ""
        self.start_time = None
        self.game_running = False
        self.first_boot = True
        
        self.main_container = tk.Frame(self.root, bg="#1e1e2e")
        self.main_container.pack(fill=tk.BOTH, expand=True)
        
        self.show_home_screen()

    def play_audio(self, filename, alias, loop=False):
        if os.path.exists(filename):
            self.mci(f'open "{filename}" type mpegvideo alias {alias}', None, 0, 0)
            command = f'play {alias} repeat' if loop else f'play {alias}'
            self.mci(command, None, 0, 0)

    def stop_audio(self, alias):
        self.mci(f'stop {alias}', None, 0, 0)
        self.mci(f'close {alias}', None, 0, 0)

    def clean_container(self):
        for widget in self.main_container.winfo_children():
            widget.destroy()

    def show_home_screen(self):
        if self.game_running or self.first_boot:
            self.stop_audio("bgmusic")
            self.stop_audio("victory")
            self.play_audio("victory_sound.mp3", "victory", loop=True)
            self.first_boot = False
            
        self.game_running = False
        self.clean_container()
        
        title = tk.Label(self.main_container, text="TYPING SPEED TEST", font=("Helvetica", 26, "bold"), fg="#f1fa8c", bg="#1e1e2e")
        title.pack(pady=30)
        
        desc_frame = tk.Frame(self.main_container, bg="#282a36", padx=20, pady=20, highlightbackground="#44475a", highlightthickness=1)
        desc_frame.pack(pady=20, padx=50, fill=tk.X)
        
        desc_title = tk.Label(desc_frame, text="Rules of the Test:", font=("Helvetica", 14, "bold"), fg="#50fa7b", bg="#282a36")
        desc_title.pack(anchor="w")
        
        instructions = "1. Hit NEXT to move onto the verification lobby.\n2. Click START GAME to generate your test phrase.\n3. The clock tracks every millisecond.\n4. Type accurately! Mistakes decrease your accuracy score.\n5. Press Enter when finished to calculate WPM."
        desc_text = tk.Label(desc_frame, text=instructions, font=("Helvetica", 11), fg="#f8f8f2", bg="#282a36", justify="left")
        desc_text.pack(pady=10, anchor="w")
        
        next_btn = tk.Button(self.main_container, text="CONTINUE ➡️", font=("Helvetica", 14, "bold"), bg="#6272a4", fg="#f8f8f2",
                             activebackground="#bd93f9", relief="flat", padx=25, pady=10, command=self.show_start_screen)
        next_btn.pack(pady=30)

    def show_start_screen(self):
        self.clean_container()
        
        if self.game_running:
            self.stop_audio("bgmusic")
            self.stop_audio("victory")
            self.play_audio("victory_sound.mp3", "victory", loop=True)
            
        self.game_running = False
        
        # 2. Build the navigation frame cleanly
        nav_frame = tk.Frame(self.main_container, bg="#1e1e2e")
        nav_frame.pack(fill=tk.X, padx=15, pady=10)
        
        home_btn = tk.Button(nav_frame, text=" 🏠 HOME ", font=("Helvetica", 10, "bold"), bg="#ff5555", fg="white", relief="flat", command=self.show_home_screen)
        home_btn.pack(side=tk.LEFT)
        
        info_panel = tk.Frame(self.main_container, bg="#282a36", width=420, height=280)
        info_panel.pack(pady=30)
        info_panel.pack_propagate(False)
        
        lobby_title = tk.Label(info_panel, text="TEST LOBBY ACTIVE", font=("Helvetica", 16, "bold"), fg="#ff79c6", bg="#282a36")
        lobby_title.pack(pady=30)
        
        desc_lbl = tk.Label(info_panel, text="Ready to measure your\nWords Per Minute (WPM)?", font=("Helvetica", 12), fg="#f8f8f2", bg="#282a36")
        desc_lbl.pack(pady=5)
        
        start_btn = tk.Button(info_panel, text="START TEST 🚀", font=("Helvetica", 14, "bold"), bg="#50fa7b", fg="#282a36",
                              padx=20, pady=10, relief="flat", command=self.start_test_action)
        start_btn.pack(pady=35)

    def start_test_action(self):
        self.stop_audio("victory")
        self.play_audio("bg_music.mp3", "bgmusic", loop=True)
        
        self.game_running = True
        self.start_time = time.time()
        self.target_text = random.choice(self.sample_texts)
        
        self.setup_gameplay_ui()
        self.update_timer_loop()

    def setup_gameplay_ui(self):
        self.clean_container()
        
        control_frame = tk.Frame(self.main_container, bg="#1e1e2e")
        control_frame.pack(fill=tk.X, padx=20, pady=10)
        
        home_btn = tk.Button(control_frame, text=" 🏠 HOME ", font=("Helvetica", 9, "bold"), bg="#ff5555", fg="white", relief="flat", command=self.show_home_screen)
        home_btn.pack(side=tk.LEFT)
        
        restart_btn = tk.Button(control_frame, text=" 🔄 RESTART ", font=("Helvetica", 9, "bold"), bg="#ffb86c", fg="#282a36", relief="flat", command=self.show_start_screen)
        restart_btn.pack(side=tk.RIGHT)
        
        stats_frame = tk.Frame(self.main_container, bg="#1e1e2e")
        stats_frame.pack(fill=tk.X, pady=10)
        
        self.time_label = tk.Label(stats_frame, text="Time: 0s", font=("Helvetica", 14, "bold"), fg="#ff79c6", bg="#1e1e2e")
        self.time_label.pack(side=tk.LEFT, padx=50)
        
        text_panel = tk.Frame(self.main_container, bg="#282a36", highlightbackground="#44475a", highlightthickness=1)
        text_panel.pack(pady=15, padx=30, fill=tk.X)
        
        self.target_label = tk.Label(text_panel, text=self.target_text, font=("Helvetica", 12, "bold"), fg="#f1fa8c", bg="#282a36", wraplength=500, justify="left")
        self.target_label.pack(pady=20, padx=15)
        
        self.user_entry = tk.Entry(self.main_container, font=("Helvetica", 13), width=50, bg="#f8f8f2", fg="#282a36", relief="flat")
        self.user_entry.pack(pady=20)
        self.user_entry.bind("<Return>", lambda event: self.calculate_results())
        self.user_entry.focus_set()
        
        submit_btn = tk.Button(self.main_container, text="FINISH & SCORE ✔", font=("Helvetica", 11, "bold"), bg="#50fa7b", fg="#282a36",
                               padx=20, pady=8, relief="flat", command=self.calculate_results)
        submit_btn.pack(pady=10)

    def update_timer_loop(self):
        if self.game_running:
            elapsed = int(time.time() - self.start_time)
            self.time_label.config(text=f"Time: {elapsed}s")
            self.root.after(1000, self.update_timer_loop)

    def calculate_results(self):
        if not self.game_running:
            return
            
        end_time = time.time()
        self.game_running = False
        
        elapsed_time_seconds = end_time - self.start_time
        if elapsed_time_seconds < 1:
            elapsed_time_seconds = 1 
            
        user_input = self.user_entry.get()
        
        target_words = self.target_text.split()
        user_words = user_input.split()
        
        correct_words = 0
        for target_w, user_w in zip(target_words, user_words):
            if target_w == user_w:
                correct_words += 1
                
        total_characters = len(user_input)
        words_equivalent = total_characters / 5
        minutes = elapsed_time_seconds / 60
        raw_wpm = int(words_equivalent / minutes)
        
        total_target_words = len(target_words)
        accuracy = int((correct_words / total_target_words) * 100) if total_target_words > 0 else 0
        
        import winsound
        winsound.Beep(1000, 200)
        
        result_string = f"⏱️ Time Taken: {int(elapsed_time_seconds)} seconds\n🏽 Gross Speed: {raw_wpm} WPM\n🎯 Accuracy Rating: {accuracy}%"
        messagebox.showinfo("Test Complete!", result_string)
        
        self.show_start_screen()

if __name__ == "__main__":
    root = tk.Tk()
    app = TypingSpeedTest(root)
    root.mainloop()